# Generated by Django 4.0.5 on 2022-06-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexbook', '0005_alter_message_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='posted_on',
            new_name='date',
        ),
    ]
